# Setup
title:               Maratom's tech Blog
tagline:             'For better'
description:         <a href="https://github.com/HyoSup0513"><img src="/public/giticon.png" width="60" height="60"></a>
url:                 "https://hyosup0513.github.io/"
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              HyoSup Cho
  url:               
  email:             ysyt2004@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
